name: game_box_flutter
description: gameBoxApolication.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3 #图标库
  provider: ^4.0.0 #状态管理
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.1.0+1
  # https://github.com/Sky24n/common_utils
#  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
#  common_utils: ^1.1.3
  flustars: ^0.3.2 #common和flustars是 一个 包含日期，正则，倒计时，时间轴等工具类 包含 SpUtil ScreenUtil WidgetUtil ImageUtil DirectoryUtil  DioUtil
  #提示
  fluttertoast: ^4.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9
  json_serializable: ^2.0.0 #json自动生成

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf


